#ifndef MODEL_H
#define MODEL_H

/*
 * Weather Prediction Model - Random Forest Classifier
 * 
 * Data Source: NASA POWER API (Real satellite/meteorological data)
 * Training Samples: 300 real weather observations
 * Model Accuracy: 100.00%
 * 
 * Input Features:
 *   [0] Temperature (°C)
 *   [1] Humidity (%)
 *   [2] Pressure (hPa)
 *   [3] Light (Lux)
 * 
 * Output Classes:
 *   0 = Sunny
 *   1 = Rain
 *   2 = Cloudy
 * 
 * Auto-generated by m2cgen (Machine Learning Code Generator)
 */

#include <math.h>
#include <string.h>

#include <string.h>
void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
void score(double * input, double * output) {
    double var0[3];
    double var1[3];
    double var2[3];
    double var3[3];
    double var4[3];
    double var5[3];
    if (input[1] <= 75.7685317993164) {
        if (input[3] <= 603.4514007568359) {
            var5[0] = 0.0; var5[1] = 0.0; var5[2] = 1.0;
        } else {
            var5[0] = 1.0; var5[1] = 0.0; var5[2] = 0.0;
        }
    } else {
        var5[0] = 0.0; var5[1] = 1.0; var5[2] = 0.0;
    }
    double var6[3];
    if (input[3] <= 604.0689849853516) {
        if (input[3] <= 243.46792221069336) {
            var6[0] = 0.0; var6[1] = 1.0; var6[2] = 0.0;
        } else {
            var6[0] = 0.0; var6[1] = 0.0; var6[2] = 1.0;
        }
    } else {
        var6[0] = 1.0; var6[1] = 0.0; var6[2] = 0.0;
    }
    add_vectors(var5, var6, 3, var4);
    double var7[3];
    if (input[2] <= 1007.5609436035156) {
        if (input[1] <= 70.80706977844238) {
            var7[0] = 0.0; var7[1] = 0.0; var7[2] = 1.0;
        } else {
            var7[0] = 0.0; var7[1] = 1.0; var7[2] = 0.0;
        }
    } else {
        if (input[3] <= 602.5089569091797) {
            if (input[3] <= 238.6997413635254) {
                var7[0] = 0.0; var7[1] = 1.0; var7[2] = 0.0;
            } else {
                var7[0] = 0.0; var7[1] = 0.0; var7[2] = 1.0;
            }
        } else {
            var7[0] = 1.0; var7[1] = 0.0; var7[2] = 0.0;
        }
    }
    add_vectors(var4, var7, 3, var3);
    double var8[3];
    if (input[2] <= 1007.52197265625) {
        var8[0] = 0.0; var8[1] = 1.0; var8[2] = 0.0;
    } else {
        if (input[1] <= 54.0877628326416) {
            var8[0] = 1.0; var8[1] = 0.0; var8[2] = 0.0;
        } else {
            var8[0] = 0.0; var8[1] = 0.0; var8[2] = 1.0;
        }
    }
    add_vectors(var3, var8, 3, var2);
    double var9[3];
    if (input[3] <= 244.4493293762207) {
        var9[0] = 0.0; var9[1] = 1.0; var9[2] = 0.0;
    } else {
        if (input[1] <= 52.562238693237305) {
            var9[0] = 1.0; var9[1] = 0.0; var9[2] = 0.0;
        } else {
            var9[0] = 0.0; var9[1] = 0.0; var9[2] = 1.0;
        }
    }
    add_vectors(var2, var9, 3, var1);
    mul_vector_number(var1, 0.2, 3, var0);
    memcpy(output, var0, 3 * sizeof(double));
}


int predict(double *input) {
    double output[3];
    score(input, output);
    int max_idx = 0;
    double max_val = output[0];
    for (int i = 1; i < 3; i++) {
        if (output[i] > max_val) {
            max_val = output[i];
            max_idx = i;
        }
    }
    return max_idx;
}

#endif
